- id: 400
  key: bank
  currency: brl
  sort_order: 1
  bank_accounts:
    -
      bank: 'Banco Itaú Unibanco S.A.'
      branch: '8888'
      holder: 'Your Account Holder'
      account: '88888-8'

- id: 401
  key: tronipay
  currency: brl
  sort_order: 13

- id: 402
  key: pagpay
  currency: brl
  sort_order: 14

- id: 403
  key: pagueveloz
  currency: brl
  sort_order: 15
  
- id: 500
  key: btc
  currency: btc
  sort_order: 2
  min_confirm: 1
  max_confirm: 3

- id: 600
  key: bch
  currency: bch
  sort_order: 3
  min_confirm: 3
  max_confirm: 3

- id: 700
  key: btg
  currency: btg
  sort_order: 4
  min_confirm: 3
  max_confirm: 3

- id: 800
  key: dash
  currency: dash
  sort_order: 5
  min_confirm: 3
  max_confirm: 3

- id: 900
  key: eth
  currency: eth
  sort_order: 6
  min_confirm: 3
  max_confirm: 3

- id: 1000
  key: zec
  currency: zec
  sort_order: 7
  min_confirm: 3
  max_confirm: 3

- id: 1100
  key: dgb
  currency: dgb
  sort_order: 8
  min_confirm: 3
  max_confirm: 3

- id: 1200
  key: xrp
  currency: xrp
  sort_order: 9
  min_confirm: 3
  max_confirm: 3

- id: 1300
  key: smart
  currency: smart
  sort_order: 10
  min_confirm: 3
  max_confirm: 3

#- id: 1400
#  key: iota
#  currency: iota
#  sort_order: 11
#  min_confirm: 3
#  max_confirm: 3


- id: 1500
  key: ltc
  currency: ltc
  sort_order: 12
  min_confirm: 3
  max_confirm: 3
  
- id: 1600
  key: zcr
  currency: zcr
  sort_order: 16
  min_confirm: 3
  max_confirm: 3

- id: 1700
  key: tusd
  currency: tusd
  sort_order: 17
  min_confirm: 3
  max_confirm: 3

- id: 1800
  key: xem
  currency: xem
  sort_order: 18
  min_confirm: 3
  max_confirm: 3

- id: 1900
  key: rbtc
  currency: rbtc
  sort_order: 19
  min_confirm: 3
  max_confirm: 3

- id: 2000
  key: rif
  currency: rif
  sort_order: 20
  min_confirm: 3
  max_confirm: 3

- id: 2100
  key: xar
  currency: xar
  sort_order: 21
  min_confirm: 3
  max_confirm: 3